server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024


keycloak:
  realm: SpringBootKeycloak
  auth-server-url: http://localhost:8180/auth
  resource: kvision-login
  bearer-only: true